import turtle
window = turtle.Screen()
marty = turtle.Turtle()


marty.color("red")
marty.circle(20)
marty.penup()
marty.goto(0, -20)
marty.pendown()
marty.color("sandy brown")
marty.circle(40)
marty.penup()
marty.goto(0, -40)
marty.pendown()
marty.color("gold")
marty.circle(60)
marty.penup()
marty.goto(0, -60)
marty.pendown()
marty.color("spring green")
marty.circle(80)
marty.penup()
marty.goto(0, -80)
marty.pendown()
marty.color("blue")
marty.circle(100)
marty.penup()
marty.goto(0, -100)
marty.pendown()
marty.color("indigo")
marty.circle(120)
marty.penup()
marty.goto(0, -120)
marty.pendown()
marty.color("violet")
marty.circle(140)
